# Sets DYLD_LIBRARY_PATH so lal's .so extensions find their C libraries.
# Generated by scripts/build_lal_wheels.sh — update the path if you
# rebuild lal to a different prefix.
import os
_lal_lib = os.path.join(
    os.path.dirname(__file__), "..", ".lal-build", "install", "lib"
)
os.environ.setdefault(
    "DYLD_LIBRARY_PATH",
    os.path.abspath(_lal_lib) + ":" + os.environ.get("DYLD_LIBRARY_PATH", ""),
)
